FROM nvidia/cuda:12.1.1-runtime-ubuntu20.04

RUN apt-get update && apt-get install -y python3 python3-pip git

WORKDIR /workspace

COPY . .

RUN pip install --no-cache-dir torch transformers

CMD ["/bin/bash"]